[package]
name = "devinit"
description = "Quickly initialise files and folders with preconfigured boilerplate templates"

edition = "2018"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
serde_yaml = "0.9.34"
